// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ParkingLotSystem.API.Data;

#nullable disable

namespace ParkingLotSystem.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ParkingLotSystem.API.Domain.Entities.Floor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FloorNumber")
                        .HasColumnType("int");

                    b.Property<int>("ParkingLotId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParkingLotId");

                    b.ToTable("Floors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FloorNumber = 1,
                            ParkingLotId = 1
                        },
                        new
                        {
                            Id = 2,
                            FloorNumber = 2,
                            ParkingLotId = 1
                        });
                });

            modelBuilder.Entity("ParkingLotSystem.API.Domain.Entities.ParkingLot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("ParkingLots");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Cairo, Egypt",
                            Name = "Cairo Mall Parking"
                        });
                });

            modelBuilder.Entity("ParkingLotSystem.API.Domain.Entities.ParkingTicket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EntryTime")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("ExitTime")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal?>("FeeCharged")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("FeeType")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("ParkingSpotId")
                        .HasColumnType("int");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParkingSpotId");

                    b.HasIndex("VehicleId");

                    b.ToTable("ParkingTickets");
                });

            modelBuilder.Entity("ParkingLotSystem.API.Domain.Entities.Spots.ParkingSpot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("varchar(13)");

                    b.Property<int>("FloorId")
                        .HasColumnType("int");

                    b.Property<bool>("IsOccupied")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SpotNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FloorId");

                    b.ToTable("ParkingSpots");

                    b.HasDiscriminator().HasValue("ParkingSpot");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("ParkingLotSystem.API.Domain.Entities.Vehicles.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("varchar(13)");

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("OwnerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Vehicles");

                    b.HasDiscriminator().HasValue("Vehicle");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("ParkingLotSystem.API.Domain.Entities.Spots.CompactSpot", b =>
                {
                    b.HasBaseType("ParkingLotSystem.API.Domain.Entities.Spots.ParkingSpot");

                    b.ToTable("ParkingSpots");

                    b.HasDiscriminator().HasValue("Compact");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FloorId = 1,
                            IsOccupied = false,
                            SpotNumber = "F1-C1",
                            Type = 0
                        },
                        new
                        {
                            Id = 2,
                            FloorId = 1,
                            IsOccupied = false,
                            SpotNumber = "F1-C2",
                            Type = 0
                        },
                        new
                        {
                            Id = 6,
                            FloorId = 2,
                            IsOccupied = false,
                            SpotNumber = "F2-C1",
                            Type = 0
                        });
                });

            modelBuilder.Entity("ParkingLotSystem.API.Domain.Entities.Spots.HandicappedSpot", b =>
                {
                    b.HasBaseType("ParkingLotSystem.API.Domain.Entities.Spots.ParkingSpot");

                    b.ToTable("ParkingSpots");

                    b.HasDiscriminator().HasValue("Handicapped");

                    b.HasData(
                        new
                        {
                            Id = 5,
                            FloorId = 1,
                            IsOccupied = false,
                            SpotNumber = "F1-H1",
                            Type = 2
                        },
                        new
                        {
                            Id = 9,
                            FloorId = 2,
                            IsOccupied = false,
                            SpotNumber = "F2-H1",
                            Type = 2
                        },
                        new
                        {
                            Id = 10,
                            FloorId = 2,
                            IsOccupied = false,
                            SpotNumber = "F2-H2",
                            Type = 2
                        });
                });

            modelBuilder.Entity("ParkingLotSystem.API.Domain.Entities.Spots.LargeSpot", b =>
                {
                    b.HasBaseType("ParkingLotSystem.API.Domain.Entities.Spots.ParkingSpot");

                    b.ToTable("ParkingSpots");

                    b.HasDiscriminator().HasValue("Large");

                    b.HasData(
                        new
                        {
                            Id = 3,
                            FloorId = 1,
                            IsOccupied = false,
                            SpotNumber = "F1-L1",
                            Type = 1
                        },
                        new
                        {
                            Id = 4,
                            FloorId = 1,
                            IsOccupied = false,
                            SpotNumber = "F1-L2",
                            Type = 1
                        },
                        new
                        {
                            Id = 7,
                            FloorId = 2,
                            IsOccupied = false,
                            SpotNumber = "F2-L1",
                            Type = 1
                        },
                        new
                        {
                            Id = 8,
                            FloorId = 2,
                            IsOccupied = false,
                            SpotNumber = "F2-L2",
                            Type = 1
                        });
                });

            modelBuilder.Entity("ParkingLotSystem.API.Domain.Entities.Vehicles.Car", b =>
                {
                    b.HasBaseType("ParkingLotSystem.API.Domain.Entities.Vehicles.Vehicle");

                    b.ToTable("Vehicles");

                    b.HasDiscriminator().HasValue("Car");
                });

            modelBuilder.Entity("ParkingLotSystem.API.Domain.Entities.Vehicles.Motorcycle", b =>
                {
                    b.HasBaseType("ParkingLotSystem.API.Domain.Entities.Vehicles.Vehicle");

                    b.ToTable("Vehicles");

                    b.HasDiscriminator().HasValue("Motorcycle");
                });

            modelBuilder.Entity("ParkingLotSystem.API.Domain.Entities.Vehicles.Truck", b =>
                {
                    b.HasBaseType("ParkingLotSystem.API.Domain.Entities.Vehicles.Vehicle");

                    b.ToTable("Vehicles");

                    b.HasDiscriminator().HasValue("Truck");
                });

            modelBuilder.Entity("ParkingLotSystem.API.Domain.Entities.Floor", b =>
                {
                    b.HasOne("ParkingLotSystem.API.Domain.Entities.ParkingLot", "ParkingLot")
                        .WithMany("Floors")
                        .HasForeignKey("ParkingLotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParkingLot");
                });

            modelBuilder.Entity("ParkingLotSystem.API.Domain.Entities.ParkingTicket", b =>
                {
                    b.HasOne("ParkingLotSystem.API.Domain.Entities.Spots.ParkingSpot", "ParkingSpot")
                        .WithMany()
                        .HasForeignKey("ParkingSpotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ParkingLotSystem.API.Domain.Entities.Vehicles.Vehicle", "Vehicle")
                        .WithMany("Tickets")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ParkingSpot");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("ParkingLotSystem.API.Domain.Entities.Spots.ParkingSpot", b =>
                {
                    b.HasOne("ParkingLotSystem.API.Domain.Entities.Floor", "Floor")
                        .WithMany("ParkingSpots")
                        .HasForeignKey("FloorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Floor");
                });

            modelBuilder.Entity("ParkingLotSystem.API.Domain.Entities.Floor", b =>
                {
                    b.Navigation("ParkingSpots");
                });

            modelBuilder.Entity("ParkingLotSystem.API.Domain.Entities.ParkingLot", b =>
                {
                    b.Navigation("Floors");
                });

            modelBuilder.Entity("ParkingLotSystem.API.Domain.Entities.Vehicles.Vehicle", b =>
                {
                    b.Navigation("Tickets");
                });
#pragma warning restore 612, 618
        }
    }
}
